### PR TITLE
Add pixel unit to padding property of body tag css

### LINKED ISSUE #41: Pixel unit missing on body
From @Lawrence4code

Reference:
https://stackoverflow.com/questions/11274904/fallback-for-css-attributes-without-unit

### PR DESCRIPTION
**Pull request by Lawrence4code**
Fixes #41 

Pixel unit was missing for body tag css in script.js file.

Reference:
https://stackoverflow.com/questions/11274904/fallback-for-css-attributes-without-unit

### CODE REVIEW

**Comment by p1ho** [comment]
Thank you for catching that! 
Can you also commit the minimized version of the file?
You can do this by running `$ ./Makefile concat` in the project directory
This will update `md-pages.js` which is the built version of the script.

**Comment by Lawrence4code** [comment]
Added build version of the script. Please take a look. I am also interested in adding cases with Jest, which I'll take up next.

**Comment by Lawrence4code** [comment]
Is there any else to be done to have to PR accepted? Please let me know.

**Comment by oscarmorrison** [comment]
Thanks @Lawrence4code 

I just created a ticket for this, I like have a ref ticket for all PR's

**Pull request merged**
