### PR TITLE
Fixing multiple anchors on one line

### LINKED ISSUE #25: Complex anchor rendered incorrectly
```
- [UpCloud ⌛](http://status.upcloud.com/) | [Cogent :airplane:](http://status.cogentco.com/)
```

redered as 

- [Cogent :airplane:](http://status.cogentco.com/)

Please advise.
Thank you.

### PR DESCRIPTION
**Pull request by szepeviktor**
...and Beautifying comments.
Fixes #25

### CODE REVIEW

**Comment by oscarmorrison** [comment]
Hi @szepeviktor thanks for the PR.

Unfortunately this broke the existing behaviour of the a href:
image


This: https://github.com/oscarmorrison/md-page/pull/26/files#diff-9a9569e9d73f33740eada95275da7f30L33 is supposed to check if url is local or external url, and then add a target="_blank" if it's external. this PR breaks that

**Comment by oscarmorrison** [comment]
Merged before I caught the bug, this PR has now been reverted. Can you please change regex, build and resubmit? 11ef84282ff0ef21dab36a1cca36c400183852f9

**Comment by szepeviktor** [comment]
Is `regex: /<a\shref[^"]+">/g,` okay?

**Comment by szepeviktor** [comment]
I am really lost here.

**Comment by oscarmorrison** [comment]
All goo @szepeviktor this fixed it https://github.com/oscarmorrison/md-page/pull/27

**Pull request merged**
