### PR TITLE
Created html rendering test cases and snapshots

### LINKED ISSUE #21: Write some tests
Would be good to have some basics tests in here.

Could just use jest, or something else. Very open to ideas

### PR DESCRIPTION
**Pull request by Leomedina**
Fixes #21 

Created HTML rendering test cases and snapshots for common markdown syntax

### CODE REVIEW

**Comment by oscarmorrison** [comment]
Hey @Leomedina thanks for doing this.

Couple of questions. This seems to be testing the showdown library its self. I am not sure we want to do that.
Ideally we want to be testing out modified converter function:
` var html = converter.makeHtml(markdown)`
https://github.com/oscarmorrison/md-page/blob/review/src/script.js#L98

**Comment by p1ho** [comment]
I think it's a good start! Thanks for your help @Leomedina!

In my mind it doesn't hurt to have some tests on the [showdown library](https://www.npmjs.com/package/showdown), since we're not importing the newest version anyway. (Actually, is there a reason we aren't doing that?)

But I agree, the focus should be on testing `src/script.js`

**Comment by Leomedina** [comment]
Thank you both! (@oscarmorrison, @p1ho) 

I actually didn't realized that showdown was from a separate library. Thanks for pointing that out - I'll go ahead and start testing the modified version.

**Comment by Leomedina** [comment]
Hey! Likely timed out because creating a new instance of JSDOM per test is _expensive_ and I'm manually waiting the load event.

I did it this way because importing the script and testing `var html = converter.makeHtml(markdown)` would result in makeHtml being `undefined` since `converter` is instantiated within the load event. 

Let me know what ya'll think! happy to rework the tests.

**Review by oscarmorrison — APPROVED** [review]
Great work @Leomedina Thanks!

**Pull request merged**
